using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace {NAMESPACE}
{{
    /// AUTOGENERATED BY caffoa
    /// <summary>
    /// Interface for service factory, useful if you need to create a service based on header or other data
    /// </summary>
    public interface {CLASSNAME}Factory
    {{
        /// <summary>
        /// returns the actual instance that handles requests
        /// </summary>
        public {CLASSNAME} Instance(HttpRequest request);

        /// <summary>
        /// returns JsonSerializerSettings that are used when serializing JSON responses.
        /// return null to use default serialization
        /// </summary>
        public JsonSerializerSettings ResponseSerializerSettings {{ get; }}
    }}
}}
