using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace {NAMESPACE}
{{
    /// AUTOGENERATED BY caffoa
    /// <summary>
    /// Interface for service factory, useful if you need to create a service based on header or other data
    /// </summary>
    public interface {CLASSNAME}Factory
    {{
        public {CLASSNAME} Instance(HttpRequest request);
    }}
}}
